pxc:
  size: 3
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "1"
  volumeSpec:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Gi
      storageClassName: "gce-pd-sc"

haproxy:
  enabled: true
  size: 3

proxysql:
  enabled: true
  size: 2

backups:
  pitr:
    enabled: true
