apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: google-secret-manager
spec:
  provider:
    gcp:
      projectID: "custom-bearing-463116-p0" # replace with your GCP project id
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: "gcp-sa-key" # Kubernetes secret that contains the SA JSON
            key: "key.json" # e.g. key.json