apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-db-secret
  namespace: wordpress
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: google-secret-manager
    kind: ClusterSecretStore
  target:
    name: wordpress-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "projects/GCP_PROJECT_ID/secrets/wordpress-db-password/versions/latest"
