apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pxc-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    chart: pxc-operator
    targetRevision: 1.18.0     # Chart version
    helm:
      releaseName: pxc-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
