# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-credentials
#   namespace: app
# type: Opaque
# data:
#   # base64 values below are examples: root: rootpass, wpuser: wpuserpass
#   MYSQL_ROOT_PASSWORD: cm9vdHBhc3M= # "rootpass" -> base64
#   MYSQL_USER: d3B1c2Vy # "wpuser"
#   MYSQL_PASSWORD: d3B1c2VycGFzcw== # "wpuserpass"
#   MYSQL_DATABASE: d3BfZGI= # "wp_db"

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-gsm-secrets
  namespace: app
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/custom-bearing-463116-p0/secrets/MYSQL_ROOT_PASSWORD/versions/latest"
        fileName: "MYSQL_ROOT_PASSWORD"
      - resourceName: "projects/custom-bearing-463116-p0/secrets/MYSQL_USER/versions/latest"
        fileName: "MYSQL_USER"
      - resourceName: "projects/custom-bearing-463116-p0/secrets/MYSQL_PASSWORD/versions/latest"
        fileName: "MYSQL_PASSWORD"
      - resourceName: "projects/custom-bearing-463116-p0/secrets/MYSQL_DATABASE/versions/latest"
        fileName: "MYSQL_DATABASE"
