apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secrets
  namespace: app
type: Opaque
stringData:
  root: rootPass123
  xtrabackup: backupPass123
  monitor: monitorPass123
  clustercheck: clusterPass123
  pmmserver: pmmPass123
  operator: operatorPass123
  replication: replPass123
