apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wordpress-route
  namespace: app
spec:
  parentRefs:
    - name: wordpress-gateway
  hostnames:
    - wordpress.example.com   # replace with your real domain    
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: wordpress-service
          port: 80