# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   namespace: app
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: filestore-sc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gcs-bucket-sc
  resources:
    requests:
      storage: 10Gi

