apiVersion: networking.gke.io/v1
kind: HealthPolicy
metadata:
  name: wordpress-health-policy
  namespace: app
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    logConfig:
      enabled: true
    config:
      type: HTTP
      requestPath: /healthz   # your custom health check path
      port: 80
