apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: wordpress-backendconfig
  namespace: app
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz    # Always 200
    port: 80
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
