apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: app
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccountName: mysql-ksa # must be bound to a GSA with Secret Manager access

      initContainers:
        - name: wait-for-filestore
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until [ -d /var/www/html ]; do echo "Waiting for Filestore..."; sleep 10; done',
            ]
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html

        - name: load-secrets
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "export WORDPRESS_DB_USER=$(cat /mnt/secrets/MYSQL_USER)" >> /workdir/wp-env.sh
              echo "export WORDPRESS_DB_PASSWORD=$(cat /mnt/secrets/MYSQL_PASSWORD)" >> /workdir/wp-env.sh
              echo "export WORDPRESS_DB_NAME=$(cat /mnt/secrets/MYSQL_DATABASE)" >> /workdir/wp-env.sh
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets
            - name: env-workdir
              mountPath: /workdir

      containers:
        - name: wordpress
          image: wordpress:6.8-apache
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "pxc-db-haproxy.app.svc.cluster.local:3306"
          command: ["sh", "-c"]
          args:
            [
              ". /workdir/wp-env.sh && exec docker-entrypoint.sh apache2-foreground",
            ]
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - name: env-workdir
              mountPath: /workdir
            - name: secrets-store-inline
              mountPath: /mnt/secrets
              readOnly: true 

      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
        - name: env-workdir
          emptyDir: {}
        - name: secrets-store-inline
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "mysql-gsm-secrets"