apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-pxc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/sumitgora/wordpressapp.git"
    targetRevision: dev
    path: "helm-values/percona"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/sumitgora/wordpressapp.git"
    targetRevision: dev
    path: "helm-values/wordpress"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
# Optional: app that deploys ExternalSecrets operator config (ClusterSecretStore)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/sumitgora/wordpressapp.git"
    targetRevision: dev
    path: "external-secrets"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
