replicaCount: 3

image:
  tag: 6.4-apache

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

persistence:
  enabled: true
  storageClass: "filestore-sc" # Filestore CSI SC you created on GKE
  accessMode: ReadWriteMany
  size: 20Gi

externalDatabase:
  host: pxc-cluster-proxysql.mysql.svc.cluster.local
  user: wordpress
  database: wordpress
  password: null # injected from ExternalSecret (see external-secrets/wordpress-externalsecret.yaml)

readinessProbe:
  httpGet:
    path: /wp-login.php
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /wp-login.php
    port: http
  initialDelaySeconds: 30
  periodSeconds: 20

# Recommended anti-affinity to spread replicas across zones/nodes
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - wordpress
      topologyKey: topology.kubernetes.io/zone
# # Ingress host (Argo CD Application can set the domain by templating this values file or you can create a kustomize overlay)
# ingress:
#   enabled: true
#   ingressClassName: gce
#   hosts:
#     - host: "DOMAIN" # replace with your domain
#       paths:
#         - path: /
#   tls:
#     - hosts:
#         - "DOMAIN"
#       secretName: wordpress-tls
